# -*- coding: utf-8 -*-
"""Program 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpZA8pNCPKLE3KgEqElDPSsLkboXyLzn
"""

!pip install gradio

import gradio as gr
import hashlib
import time

# ---- Helper functions ----
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def check_strength(password):
    if len(password) < 4:
        return "🔴 Very Weak"
    elif len(password) < 8:
        return "🟠 Moderate"
    else:
        return "🟢 Strong"

def dictionary_attack(password, dictionary, mode, progress=gr.Progress()):
    words = dictionary.splitlines()
    for i, word in enumerate(words, 1):
        progress(i / len(words))
        time.sleep(0.01)  # simulate processing

        if mode == "Plaintext" and word == password:
            return f"✔️ Password Found → {word}\nHash Value: {hash_password(word)}"
        elif mode == "Hash" and hash_password(word) == password:
            return f"✔️ Match Found → Original Word: {word}"

    return "❌ No Match Detected in Dictionary."

# ---- GUI ----
def run_attack(password, dictionary, mode):
    result = dictionary_attack(password, dictionary, mode)
    if mode == "Plaintext":
        strength = check_strength(password)
        return f"{result}\n🔑 Strength Analysis: {strength}"
    else:
        return result

with gr.Blocks(theme=gr.themes.Soft(
        primary_hue="purple",
        secondary_hue="pink",
        neutral_hue="slate"
    )) as demo:

    with gr.Row():
        gr.Markdown("## 🌙 Stylish Dictionary Attack Tool", elem_classes="title")

    with gr.Row():
        with gr.Column(scale=1):
            password = gr.Textbox(label="🔑 Input (Password or Hash)", placeholder="Type password or hash here...")
            mode = gr.Radio(["Plaintext", "Hash"], value="Plaintext", label="⚙️ Attack Mode")
            dictionary = gr.Textbox(
                label="📄 Wordlist (one entry per line)",
                value="1234\npassword\nadmin\nletmein",
                lines=6,
                interactive=True   # <-- FIX: now editable
            )
            run_btn = gr.Button("🚀 Launch Attack", variant="primary")

        with gr.Column(scale=1):
            output = gr.Textbox(label="📊 Attack Results", lines=8)

    run_btn.click(run_attack, inputs=[password, dictionary, mode], outputs=output)

demo.launch()